### ISSUE TITLE
Getting scrambled display while connecting to VNC Server from Client

### ISSUE THREAD

**Issue by kvaditya** [ponty/framebuffer-vncserver#1]
please help me in fixing this issue,
my windows PC is installed with Windows 8 64 bit, i am using Tight VNC.
![2016-07-20 16_15_28-framebuffer - tightvnc viewer](https://cloud.githubusercontent.com/assets/20556407/16984116/095fb592-4e96-11e6-8074-efa596c9dff3.png)

**Comment by ponty** [comment]
Try to restart the VNC server.

**Comment by kvaditya** [comment]
okay, thank u, i fixed that color issue, can you suggest why will we get, 

1000 .... = Rectangle type: 0x08 (fill encoding - solid rectangle)

when we see in wire shark.

**Comment by ponty** [comment]
I have no idea, but I have not much knowledge about VNC.

**Comment by kvaditya** [comment]
Oh, its ok thank u :)
