### ISSUE TITLE
Compresison

### ISSUE THREAD

**Issue by zwick88** [ponty/framebuffer-vncserver#12]
Hi, 

is there any way to change the compression or to turn it off

Alex

**Comment by ponty** [comment]
There is no such parameter currently implemented. If libvncserver has support for it then it can be added. 
You can try to set the compression level in the client.

I found this:  https://www.tightvnc.com/vncviewer.1.php
```
vncviewer -compresslevel level
```
"Use specified compression level (0..9) for "tight" and "zlib" encodings..."
