### ISSUE TITLE
[FR] Rotate display

### ISSUE THREAD

**Issue by pc-coholic** [ponty/framebuffer-vncserver#2]
Hello!

I've tried to implement this myself - but was not very successful doing so... That's why I am opening this feature request :-)

If you have some spare time on your hands, perhaps you could implement a command line-switch to have the display rotated.

A little background: I am using your vnc-implementation to run on an vending machine, that has the display mounted vertically - so having the screen transmitted rotated would be quite helpful. :-)

**Comment by ponty** [comment]
The idea is valid, but I have no plan for implementing it (patches are welcome). 
The other option is to rotate the screen in the client, this could be easier.

**Comment by ponty** [comment]
This was implemented in #4.

**Comment by pc-coholic** [comment]
Great! Thank you, @uklatt!
