### ISSUE TITLE
Integrate forked changes

### ISSUE THREAD

**Issue by hcw70** [ponty/framebuffer-vncserver#3]
Hi @ponty . Just found about your project and I want to use it in a project context.

However, there seems to be some performance issues in the implementation. 
We have an additional load of 30% on an ARM single core.

Is there a chance to integrate some of the forked changes into your version to gain performance in the "official" version?

Some of the changes also implemented input handling.

See forks from  @shbatm  , @tobiaswaldvogel, @fhunleth, @Ultimaker and @dgburr.

**Comment by ponty** [comment]
I added as much changes as I can. I didn't added the performance forks, because I don't see how they work. It would be easier to get pull requests with explanation.
