### ISSUE TITLE
LIBVNC: LIBVNC-NOTFOUND

### ISSUE THREAD

**Issue by mongldroid** [ponty/framebuffer-vncserver#8]
when trying to compile with CMAKE i get the following error:

-----------------------------------------

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

Please set them or make sure they are set and tested correctly in the CMake files:
LIBVNC    -    linked by target "framebuffer-vncserver" in directory /home/vnc/framebuffer-vncserver-master

-----------------------------------------

I have installed the VNCLIB from https://github.com/LibVNC/libvncserver and it still will not recognize the lib present.

**Comment by ponty** [comment]
Use the package manager:

```
sudo apt-get install libvncserver-dev
```
